<?php

return [

    //Available Hooks
    "senders" => [
        "login_attempt",
        "login_successful",
        "login_failed",
        "logout_attempt",
        "logout_successful",
        "server_key_verify",
        "server_key_add",
        "server_add_attempt",
        "server_add_successful",
        "server_update",
        "server_delete",
        "server_extension_add",
        "server_extension_remove",
        "extension_upload_attempt",
        "extension_upload_successful",
        "extension_delete_attempt",
        "extension_delete_successful",
        "user_add_attempt",
        "user_add_successful",
        "user_delete_attempt",
        "user_delete_successful",
        "user_password_reset_attempt",
        "user_password_reset_successful",
        "role_group_add_attempt",
        "role_group_add_successful",
        "user_to_role_group_attempt",
        "user_to_role_group_successful",
        "delete_user_from_role_group_attempt",
        "delete_user_from_role_group_successful",
        "role_group_extension_grant_attempt",
        "role_group_extension_grant_successful",
        "role_group_extension_revoke_attempt",
        "role_group_extension_revoke_successful",
        "role_group_server_grant_attempt",
        "role_group_server_grant_successful",
        "role_group_server_revoke_attempt",
        "role_group_server_revoke_successful",
        "role_group_function_grant_attempt",
        "role_group_function_grant_successful",
        "role_group_function_revoke_attempt",
        "role_group_function_revoke_successful",
        "server_group_create_attempt",
        "server_group_create_successful",
        "server_group_update_attempt",
        "server_group_update_successful",
        "server_group_remove_attempt",
        "server_group_remove_successful",
        "certificate_add_attempt",
        "certificate_add_successful",
        "certificate_renew_attempt",
        "certificate_renew_successful",
        "certificate_revoke_attempt",
        "certificate_revoke_successful",
        "health_problem",
        "new_liman_update",
        "wallet_cache_clear_attempt",
        "wallet_cache_clear_successful",
        "wallet_new_key_add_attempt",
        "wallet_new_key_add_successful",
        "wallet_setting_add_attempt",
        "wallet_setting_add_successful",
        "wallet_setting_update_attempt",
        "wallet_setting_update_successful",
        "wallet_setting_delete_attempt",
        "wallet_setting_delete_successful"
    ],

    "listeners" => [
        "user_create",
        "user_update",
        "user_delete",
        "server_add",
        "server_update",
        "server_delete",
        "server_extension_add",
        "server_extension_remove",
        "extension_add",
        "extension_remove",
        "certificate_add",
        "certificate_remove"
    ],

    // Hooks execute timeout
    "timeout" => 5
];