apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    service: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      service: db
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        network/liman-net: "true"
        service: db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: liman
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: {{ .Release.Name }}-auth
            - name: POSTGRES_USER
              value: liman
          image: postgres:15
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -q
                - -d
                - liman
                - -U
                - liman
            failureThreshold: 5
            periodSeconds: 5
            timeoutSeconds: 5
          name: liman-db
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db
      restartPolicy: Always
      volumes:
        - name: db
          persistentVolumeClaim:
            claimName: db
status: {}
