apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: limancore
spec:
  replicas: 1
  selector:
    matchLabels:
      network/liman-net: "true"
      service: limancore
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        network/liman-net: "true"
        service: limancore
    spec:
      initContainers:
      - name: wait-for
        image: ghcr.io/patrickdappollonio/wait-for:latest
        env:
        - name: POSTGRES_HOST
          value: "liman-db:5432"
        - name: REDIS_HOST
          value: "liman-redis:6379"
        command:
          - /wait-for
        args:
          - --host="$(REDIS_HOST)"
          - --host="$(POSTGRES_HOST)"
          - -v
          - -e10s
          - -t120s
      containers:
        - env:
            - name: DB_DATABASE
              value: liman
            - name: DB_HOST
              value: liman-db
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  key: password
                  name: {{ .Release.Name }}-auth
            - name: DB_PORT
              value: "5432"
            - name: DB_USERNAME
              value: liman
            - name: NGINX_PORT
              value: "443"
            - name: REDIS_HOST
              value: liman-redis
            - name: REDIS_PASS
              valueFrom:
                secretKeyRef:
                  key: password
                  name: {{ .Release.Name }}-auth
            - name: REDIS_PORT
              value: "6379"
          image: aciklab/liman:latest
          name: liman-core
          ports:
            - containerPort: 443
              protocol: TCP
          resources: {}
          tty: true
          volumeMounts:
            - mountPath: /liman
              name: core
            - mountPath: /usr/local/share/ca-certificates
              name: certs
      restartPolicy: Always
      volumes:
        - name: core
          persistentVolumeClaim:
            claimName: core
        - name: certs
          persistentVolumeClaim:
            claimName: certs
status: {}
