apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: limancore
  name: limancore
spec:
  ports:
    - name: "443"
      port: 443
      targetPort: 443
      nodePort: 30443
  type: NodePort
  selector:
    service: limancore
status:
  loadBalancer: {}
