#!/bin/bash
chmod o+xr /liman/
chmod -R o+xr /liman/sandbox
chmod o+x /liman/extensions

mv /liman/server/nginx.conf /etc/nginx/sites-available/liman.conf
ln -s /etc/nginx/sites-available/liman.conf /etc/nginx/sites-enabled/liman.conf

systemctl restart nginx
systemctl enable nginx
systemctl restart php7.3-fpm
php /liman/server/artisan migrate --force
chown -R liman:liman /liman/{server,database,certs,keys/windows,keys/linux,sandbox,logs}
chmod 700 -R /liman/{server,database,certs,keys/windows,keys/linux,logs}
chmod 755 -R /liman/sandbox
chmod 755 /liman/keys
systemctl restart nginx
systemctl enable nginx
printf "\nKurulum Tamamlandı\n\nYönetici Hesabı oluşturmak yada şifrenizi yenilemek için aşağıdaki komutu çalıştırabilisiniz\n\n\n"
echo "sudo runuser liman -c \"php /liman/server/artisan administrator\""