#!/bin/bash

# Folder Creation

mkdir -p /liman/{server,certs,logs,database,sandbox,keys,extensions}
mkdir -p /liman/keys/{windows,linux}

# User Creation
if getent passwd liman > /dev/null 2>&1; then
    echo "Liman User Found."
else
    useradd liman -m
    mkdir /home/liman
    chmod -R o= /liman /home/liman
    chown -R liman:liman /liman /home/liman
    echo "liman     ALL=(ALL:ALL) NOPASSWD:ALL" >> /etc/sudoers
    echo "Liman User Created"
fi

# Certificate Creation
if [ -f "/liman/certs/liman.crt" ]; then
    echo "SSL Certificate Found."
else
    openssl req \
        -new \
        -newkey rsa:4096 \
        -days 365 \
        -nodes \
        -x509 \
        -subj "/C=TR/ST=Ankara/L=Merkez/O=Havelsan/CN=liman" \
        -keyout /liman/certs/liman.key \
        -out /liman/certs/liman.crt
    echo "SSL Certificate Created"
fi

# Database Creation
if [ -f "/liman/database/liman.sqlite" ]; then
    echo "Database file found."
else
    touch /liman/database/liman.sqlite
    chmod 700 /liman/database/liman.sqlite
fi

sed -i "s/www-data/liman/g" /etc/php/7.3/fpm/pool.d/www.conf
sed -i "s/www-data/liman/g" /etc/nginx/nginx.conf

# Ldap Setting
if [ ! -z $(grep "TLS_REQCERT" "/etc/ldap/ldap.conf") ]; then 
    echo "FOUND"; 
else
    sudo echo "TLS_REQCERT     never" | sudo tee --append /etc/ldap/ldap.conf
fi



